// The one-time setup script an operator runs as root on each server, generated
// per server by GET /servers/:id/bootstrap. It is the whole on-host footprint
// of the server console, so it is written to be read before it's run.
//
// Trust model, outermost first:
//   1. authorized_keys pins the workspace key to SERVER_SSH_SOURCE_IP (from=),
//      strips pty/forwarding (restrict) and forces every login through
//      mbp-dispatch (command=). The key can never get a shell.
//   2. mbp-dispatch allows a fixed list of verbs; mutating verbs are refused
//      when /etc/mbp/mode says read-only.
//   3. sudoers lets mbp-ops run exactly those root-owned scripts with NO
//      arguments (the trailing "" in sudoers syntax), so nothing the workspace
//      sends can become part of a root command line.
//   4. Read-only servers get no mutating scripts and no sudo rule for them.
//
// Long-running work (update, upgrade, scan, reboot) runs as a transient
// systemd unit, mbp-job, so it survives the SSH session or the API restarting
// mid-upgrade. A killed dpkg can leave a server half-upgraded.
//
// NOTE: the script is a TypeScript String.raw template. Bash's brace expansion
// syntax would be read as template interpolation, so the bash below avoids it
// entirely (plain $var, no arrays). Keep it that way when editing.

export interface BootstrapOptions {
  serverName: string;
  mode: "managed" | "read-only";
  /** HH:MM (UTC) for unattended-upgrades' automatic reboot; "" leaves it alone. */
  rebootTime: string;
  sourceIp: string;
  publicKey: string;
}

// Shell-quote for a single-quoted bash literal.
const q = (s: string) => s.replace(/'/g, `'"'"'`);

export function bootstrapScript(o: BootstrapOptions): string {
  return SCRIPT.replace("__NAME__", o.serverName.replace(/[\r\n]/g, " "))
    .replace("__MODE__", q(o.mode))
    .replace("__REBOOT_TIME__", q(o.rebootTime))
    .replace("__SOURCE_IP__", q(o.sourceIp))
    .replace("__PUBKEY__", q(o.publicKey));
}

const SCRIPT = String.raw`#!/usr/bin/env bash
# MyBizPush workspace: server bootstrap for "__NAME__"
#
# Generated by the Dev Space server console. Run once, as root:
#   sudo bash mbp-bootstrap.sh
# Re-running is safe and is how you apply an updated version: every step
# checks before it changes anything.
set -euo pipefail

MODE='__MODE__'               # managed | read-only
REBOOT_TIME='__REBOOT_TIME__' # HH:MM UTC for automatic security reboots; empty = leave as is
SOURCE_IP='__SOURCE_IP__'
PUBKEY='__PUBKEY__'
OPS_USER=mbp-ops
DOCKER_PKGS="docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras"

say() { printf '\n\033[1;35m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash $0"
. /etc/os-release
case "$ID" in ubuntu|debian) ;; *) die "Only Ubuntu and Debian are supported (found $ID)";; esac
command -v systemd-run >/dev/null || die "systemd-run is required"
[ -n "$SOURCE_IP" ] || die "No source IP: set SERVER_SSH_SOURCE_IP on the workspace API and download this script again"
case "$MODE" in managed|read-only) ;; *) die "Unknown mode $MODE";; esac

say "Mode: $MODE"

# ---------------------------------------------------------------- account
say "Account $OPS_USER"
if ! id "$OPS_USER" >/dev/null 2>&1; then
  useradd --create-home --shell /bin/bash "$OPS_USER"
  echo "  created"
fi
# No password, but NOT locked ('*', not '!'): sshd refuses key logins to a
# locked account when PAM is off.
usermod -p '*' "$OPS_USER"
home=$(getent passwd "$OPS_USER" | cut -d: -f6)
# Root-owned, so nothing running as mbp-ops can add itself another key.
install -d -m 755 -o root -g root "$home/.ssh"
printf 'from="%s",restrict,command="/usr/local/sbin/mbp-dispatch" %s\n' "$SOURCE_IP" "$PUBKEY" > "$home/.ssh/authorized_keys"
chown root:root "$home/.ssh/authorized_keys"
chmod 644 "$home/.ssh/authorized_keys"
echo "  key installed, usable only from $SOURCE_IP"

# ------------------------------------------------------------- sshd access
say "SSH access"
changed=0
for f in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf; do
  [ -f "$f" ] || continue
  if grep -qiE '^[[:space:]]*AllowUsers[[:space:]]' "$f" && ! grep -qiE "^[[:space:]]*AllowUsers.*[[:space:]]$OPS_USER([[:space:]]|$)" "$f"; then
    sed -i -E "s/^([[:space:]]*AllowUsers[[:space:]].*)$/\1 $OPS_USER/I" "$f"
    echo "  added $OPS_USER to AllowUsers in $f"
    changed=1
  fi
done
if grep -qiE '^[[:space:]]*(AllowGroups|DenyUsers|DenyGroups)[[:space:]]' /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf 2>/dev/null; then
  echo "  NOTE: AllowGroups/DenyUsers/DenyGroups is set; check it doesn't exclude $OPS_USER"
fi
if [ "$changed" = 1 ]; then
  sshd -t || die "sshd config test failed; nothing reloaded"
  systemctl reload ssh 2>/dev/null || systemctl reload sshd
  echo "  sshd reloaded"
else
  echo "  no AllowUsers change needed"
fi

# ----------------------------------------------------------------- scripts
say "Scripts"
install -d -m 755 /etc/mbp /usr/local/lib/mbp
install -d -m 750 /var/lib/mbp
echo "$MODE" > /etc/mbp/mode
chmod 644 /etc/mbp/mode

put() { cat > "$1"; chown root:root "$1"; chmod "$2" "$1"; }

put /usr/local/sbin/mbp-dispatch 755 <<'EOF'
#!/bin/bash
# Forced command for the workspace key. The only things it can run.
cmd=$(printenv SSH_ORIGINAL_COMMAND || true)
mode=$(cat /etc/mbp/mode 2>/dev/null || echo read-only)
case "$cmd" in
  stats|job-status|scan) ;;
  update|upgrade|upgrade-docker|reboot)
    if [ "$mode" != managed ]; then
      echo "mbp: this server is read-only in the workspace" >&2
      exit 126
    fi ;;
  *)
    logger -t mbp "refused command: $cmd"
    echo "mbp: command not allowed" >&2
    exit 126 ;;
esac
exec sudo -n "/usr/local/sbin/mbp-$cmd"
EOF

put /usr/local/lib/mbp/start-job 700 <<'EOF'
#!/bin/bash
# Start a job as the transient unit mbp-job. One at a time per server.
set -eu
kind="$1"
dir=/var/lib/mbp
if systemctl is-active --quiet mbp-job.service; then
  echo "busy=$(cat "$dir/job.kind" 2>/dev/null)"
  exit 75
fi
rm -f "$dir/job.exit" "$dir/job.result" "$dir/job.log"
echo "$kind" > "$dir/job.kind"
date -u +%s > "$dir/job.started"
systemd-run --unit=mbp-job --collect --quiet /usr/local/lib/mbp/run-job "$kind"
echo "started=$(cat "$dir/job.started")"
EOF

put /usr/local/lib/mbp/run-job 700 <<'EOF'
#!/bin/bash
kind="$1"
dir=/var/lib/mbp
exec > "$dir/job.log" 2>&1
echo "== $kind started $(date -u +%FT%TZ) on $(hostname)"
"/usr/local/lib/mbp/job-$kind"
rc=$?
echo "== $kind finished with exit code $rc at $(date -u +%FT%TZ)"
echo "$rc" > "$dir/job.exit"
exit "$rc"
EOF

put /usr/local/sbin/mbp-job-status 755 <<'EOF'
#!/bin/bash
dir=/var/lib/mbp
if [ ! -f "$dir/job.kind" ]; then echo "state=none"; exit 0; fi
echo "kind=$(cat "$dir/job.kind")"
echo "started=$(cat "$dir/job.started" 2>/dev/null)"
if [ -f "$dir/job.exit" ]; then
  echo "state=finished"
  echo "exit=$(cat "$dir/job.exit")"
elif systemctl is-active --quiet mbp-job.service; then
  echo "state=running"
else
  echo "state=lost"
fi
echo "@@result"
cat "$dir/job.result" 2>/dev/null
echo "@@log"
tail -n 400 "$dir/job.log" 2>/dev/null
EOF

put /usr/local/sbin/mbp-stats 755 <<'EOF'
#!/bin/bash
# Health and patch state as key=value lines. Read-only: changes nothing.
export LC_ALL=C
kv() { printf '%s=%s\n' "$1" "$2"; }
. /etc/os-release
kv mbp_version 1
kv mode "$(cat /etc/mbp/mode 2>/dev/null)"
kv hostname "$(hostname)"
kv os "$PRETTY_NAME"
kv kernel_running "$(uname -r)"
kv kernel_latest "$(ls -1 /boot/vmlinuz-* 2>/dev/null | sed 's|/boot/vmlinuz-||' | sort -V | tail -1)"
kv uptime_seconds "$(cut -d. -f1 /proc/uptime)"
read -r l1 l5 l15 _ < /proc/loadavg
kv load1 "$l1"; kv load5 "$l5"; kv load15 "$l15"
kv cpu_count "$(nproc)"
kv mem_total_kb "$(awk '/^MemTotal:/{print $2}' /proc/meminfo)"
kv mem_available_kb "$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)"
kv swap_total_kb "$(awk '/^SwapTotal:/{print $2}' /proc/meminfo)"
kv swap_free_kb "$(awk '/^SwapFree:/{print $2}' /proc/meminfo)"
df -P -k -x tmpfs -x devtmpfs -x overlay -x squashfs -x efivarfs 2>/dev/null \
  | awk 'NR>1{print "disk=" $6 "|" $2 "|" $3 "|" $5}'

# Packages. apt's pending count alone is not patch state: held packages are
# excluded from it, and installed-but-not-rebooted kernels don't show at all.
sim=$(apt-get -s -o Debug::NoLocking=1 upgrade 2>/dev/null | grep '^Inst ' || true)
if [ -n "$sim" ]; then
  kv pending_updates "$(printf '%s\n' "$sim" | wc -l)"
  kv security_updates "$(printf '%s\n' "$sim" | grep -c -- '-security' || true)"
  printf '%s\n' "$sim" | head -300 | awk '{
    sec = ($0 ~ /-security/) ? 1 : 0
    if ($3 ~ /^\[/) { from = $3; to = $4 } else { from = ""; to = $3 }
    gsub(/[\[\]()]/, "", from); gsub(/[\[\]()]/, "", to)
    print "upgradable=" $2 "|" from "|" to "|" sec
  }'
else
  kv pending_updates 0
  kv security_updates 0
fi
for p in $(apt-mark showhold 2>/dev/null); do
  inst=$(dpkg-query -W "$p" 2>/dev/null | cut -f2)
  cand=$(apt-cache policy "$p" 2>/dev/null | awk '/Candidate:/{print $2}')
  kv held "$p|$inst|$cand"
done
if [ -f /var/run/reboot-required ]; then
  kv reboot_required 1
  kv reboot_pkgs "$(tr '\n' ' ' < /var/run/reboot-required.pkgs 2>/dev/null)"
else
  kv reboot_required 0
fi
UU=""; AR=""; ART=""
eval "$(apt-config shell UU APT::Periodic::Unattended-Upgrade AR Unattended-Upgrade::Automatic-Reboot ART Unattended-Upgrade::Automatic-Reboot-Time)"
kv unattended_enabled "$UU"
kv auto_reboot "$AR"
kv auto_reboot_time "$ART"
[ -f /var/log/unattended-upgrades/unattended-upgrades.log ] && kv unattended_last_run "$(stat -c %Y /var/log/unattended-upgrades/unattended-upgrades.log)"
# Newest index file, so a manual or workspace "apt-get update" counts too, not
# just the apt-daily timer's stamp.
newest=$(ls -t /var/lib/apt/lists/*Release 2>/dev/null | head -1)
[ -n "$newest" ] && kv apt_lists_updated "$(stat -c %Y "$newest")"
kv last_apt_activity "$(grep -h '^Start-Date:' /var/log/apt/history.log 2>/dev/null | tail -1 | cut -d' ' -f2-)"

# Services and exposure.
systemctl list-units --state=failed --no-legend --plain 2>/dev/null | awk '{print "failed_unit=" $1}'
if command -v docker >/dev/null 2>&1; then
  kv docker_version "$(docker version --format '{{.Server.Version}}' 2>/dev/null)"
  docker ps -a --format '{{.Names}}|{{.State}}|{{.Status}}|{{.Image}}' 2>/dev/null | head -200 | sed 's/^/container=/'
fi
ss -H -tulnp 2>/dev/null | awk '{
  proc = $7; sub(/^users:\(\("/, "", proc); sub(/".*/, "", proc)
  print "listen=" $1 "|" $5 "|" proc
}'
kv ufw "$(ufw status 2>/dev/null | head -1 | sed 's/^Status: //')"
if command -v fail2ban-client >/dev/null 2>&1; then
  jails=$(fail2ban-client status 2>/dev/null | sed -n 's/.*Jail list:[[:space:]]*//p' | tr -d ' ' | tr ',' ' ')
  for j in $jails; do
    st=$(fail2ban-client status "$j" 2>/dev/null)
    cur=$(printf '%s\n' "$st" | awk -F: '/Currently banned/{gsub(/[[:space:]]/, "", $2); print $2}')
    tot=$(printf '%s\n' "$st" | awk -F: '/Total banned/{gsub(/[[:space:]]/, "", $2); print $2}')
    kv f2b "$j|$cur|$tot"
  done
fi
kv ssh_failures_24h "$(journalctl -u ssh -u sshd --since -24h --no-pager -q 2>/dev/null | grep -cE 'Failed password|Invalid user|authentication failure' || true)"
sshd -T 2>/dev/null | awk '$1=="permitrootlogin" || $1=="passwordauthentication" {print "sshd_" $1 "=" $2}'
EOF

# Job starters: tiny, argument-free entry points for sudo.
for kind in scan update upgrade upgrade-docker reboot; do
  put "/usr/local/sbin/mbp-$kind" 755 <<EOF
#!/bin/bash
exec /usr/local/lib/mbp/start-job $kind
EOF
done

put /usr/local/lib/mbp/job-scan 700 <<'EOF'
#!/bin/bash
# Security scan. Reads the system; changes nothing but Lynis' own logs.
res=/var/lib/mbp/job.result
: > "$res"
if command -v lynis >/dev/null 2>&1; then
  echo "Running Lynis (a few minutes)..."
  lynis audit system --quick --no-colors --cronjob > /dev/null 2>&1 || true
  rep=/var/log/lynis-report.dat
  if [ -f "$rep" ]; then
    hi=$(grep -m1 '^hardening_index=' "$rep" | cut -d= -f2)
    echo "lynis_version=$(grep -m1 '^lynis_version=' "$rep" | cut -d= -f2)" >> "$res"
    echo "hardening_index=$hi" >> "$res"
    grep '^warning\[\]=' "$rep" | cut -d= -f2- | sed 's/^/warning=/' >> "$res"
    grep '^suggestion\[\]=' "$rep" | cut -d= -f2- | sed 's/^/suggestion=/' >> "$res"
    echo "Lynis hardening index: $hi"
    echo "Warnings: $(grep -c '^warning\[\]=' "$rep")  Suggestions: $(grep -c '^suggestion\[\]=' "$rep")"
  fi
else
  echo "lynis_missing=1" >> "$res"
  echo "Lynis is not installed, so the hardening audit was skipped."
fi
EOF

if [ "$MODE" = managed ]; then
  put /usr/local/lib/mbp/job-update 700 <<'EOF'
#!/bin/bash
set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get -o DPkg::Lock::Timeout=600 update
EOF

  put /usr/local/lib/mbp/job-upgrade 700 <<'EOF'
#!/bin/bash
set -eu
# needrestart in list mode: report services on old libraries rather than
# restarting them (restarting dockerd would restart every container).
export DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=l
OPTS="-o DPkg::Lock::Timeout=900 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
apt-get $OPTS update
apt-get $OPTS -y upgrade
apt-get $OPTS -y autoremove
if [ -f /var/run/reboot-required ]; then
  echo "A reboot is required to activate:"
  cat /var/run/reboot-required.pkgs 2>/dev/null || true
fi
EOF

  put /usr/local/lib/mbp/job-upgrade-docker 700 <<'EOF'
#!/bin/bash
set -eu
export DEBIAN_FRONTEND=noninteractive
OPTS="-o DPkg::Lock::Timeout=900 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
pkgs=""
for p in docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras; do
  dpkg -s "$p" >/dev/null 2>&1 && pkgs="$pkgs $p"
done
if [ -z "$pkgs" ]; then echo "Docker isn't installed from Docker's packages here; nothing to do."; exit 0; fi
# Hold again whatever happens, so routine upgrades keep leaving Docker alone.
trap 'apt-mark hold $pkgs >/dev/null' EXIT
echo "Upgrading:$pkgs"
echo "Containers restart while the Docker daemon is upgraded."
apt-mark unhold $pkgs
apt-get $OPTS update
apt-get $OPTS -y install --only-upgrade $pkgs
docker version --format 'Docker {{.Server.Version}} is running'
EOF

  put /usr/local/lib/mbp/job-reboot 700 <<'EOF'
#!/bin/bash
echo "Rebooting in 1 minute."
shutdown -r +1 "Reboot requested from the MyBizPush workspace"
EOF
else
  # Read-only: make sure no mutating entry point survives from an earlier run.
  rm -f /usr/local/sbin/mbp-update /usr/local/sbin/mbp-upgrade /usr/local/sbin/mbp-upgrade-docker /usr/local/sbin/mbp-reboot
  rm -f /usr/local/lib/mbp/job-update /usr/local/lib/mbp/job-upgrade /usr/local/lib/mbp/job-upgrade-docker /usr/local/lib/mbp/job-reboot
fi
echo "  installed to /usr/local/sbin/mbp-* and /usr/local/lib/mbp/"

# ------------------------------------------------------------------ sudoers
say "Sudo rule"
cmds='/usr/local/sbin/mbp-stats "", /usr/local/sbin/mbp-job-status "", /usr/local/sbin/mbp-scan ""'
if [ "$MODE" = managed ]; then
  cmds="$cmds"', /usr/local/sbin/mbp-update "", /usr/local/sbin/mbp-upgrade "", /usr/local/sbin/mbp-upgrade-docker "", /usr/local/sbin/mbp-reboot ""'
fi
tmp=$(mktemp)
printf '# Managed by the MyBizPush workspace bootstrap. Exactly these scripts, no arguments.\n%s ALL=(root) NOPASSWD: %s\n' "$OPS_USER" "$cmds" > "$tmp"
visudo -cf "$tmp" >/dev/null || { rm -f "$tmp"; die "sudoers rule failed validation; nothing installed"; }
install -m 440 -o root -g root "$tmp" /etc/sudoers.d/mbp-ops
rm -f "$tmp"
echo "  /etc/sudoers.d/mbp-ops"

# --------------------------------------------------------- managed extras
if [ "$MODE" = managed ]; then
  say "Patching"
  export DEBIAN_FRONTEND=noninteractive
  apt-get -o DPkg::Lock::Timeout=300 -qq update || true
  apt-get -o DPkg::Lock::Timeout=300 -y -qq install unattended-upgrades lynis >/dev/null || echo "  could not install unattended-upgrades/lynis; continuing"

  UU=""; AR=""
  eval "$(apt-config shell UU APT::Periodic::Unattended-Upgrade AR Unattended-Upgrade::Automatic-Reboot)"
  if [ "$UU" != 1 ]; then
    printf 'APT::Periodic::Update-Package-Lists "1";\nAPT::Periodic::Unattended-Upgrade "1";\n' > /etc/apt/apt.conf.d/20auto-upgrades
    echo "  unattended-upgrades enabled"
  else
    echo "  unattended-upgrades already enabled"
  fi
  # Installing a patch isn't applying it: kernel and libc fixes only take
  # effect after a reboot. An existing auto-reboot config is left alone.
  if [ "$AR" = true ]; then
    echo "  automatic security reboots already configured; left as is"
  elif [ -n "$REBOOT_TIME" ]; then
    printf 'Unattended-Upgrade::Automatic-Reboot "true";\nUnattended-Upgrade::Automatic-Reboot-WithUsers "true";\nUnattended-Upgrade::Automatic-Reboot-Time "%s";\n' "$REBOOT_TIME" > /etc/apt/apt.conf.d/52-mbp-autoreboot
    echo "  automatic security reboots at $REBOOT_TIME (server time) when a patch needs one"
  fi

  say "Docker packages"
  held=""
  for p in $DOCKER_PKGS; do
    if dpkg -s "$p" >/dev/null 2>&1; then apt-mark hold "$p" >/dev/null; held="$held $p"; fi
  done
  if [ -n "$held" ]; then
    echo "  held:$held"
    echo "  (routine upgrades skip Docker; use 'Upgrade Docker' in the workspace inside a quiet window)"
  else
    echo "  none installed from Docker's repository"
  fi
fi

# ------------------------------------------------------------------- done
say "Done"
echo "Server time zone: $(timedatectl show -p Timezone --value 2>/dev/null || date +%Z)"
echo "Host key fingerprints (compare with the one the workspace shows on first connect):"
for k in /etc/ssh/ssh_host_*_key.pub; do ssh-keygen -lf "$k"; done
echo
echo "Now press 'Test connection' in the workspace."
`;
